env:
  global:
    - SWIFT_BRANCH=swift-4.1.3-release
    - SWIFT_VERSION=swift-4.1.3-RELEASE
matrix:
  include:
    - os: 
      - linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - sudo apt-get install clang-3.8 libicu-dev 
        - mkdir swift
        - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar xz -C swift &> /dev/null
        - export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH"
      script:
        - swift --version
        - swift package update
        - swift build
        - swift test
        
    - os:
      - osx
      language: swift
      osx_image: xcode9.4
      install: swift package update
      script:
        - swift build
        - swift test

